#!/bin/sh -e
# Copyright (c) 2022 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core kalifix'
DESCRIPTION='Installs the default kali linux metapackage.'
HOSTBIN='kali'
CHROOTBIN='croutonpowerd'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

echo "Update the package list..."
apt-get -y -qq update

install dbus openssh-client kbd

# Install kali linux core metapackage
install kali-linux-default -- network-manager

TIPS="$TIPS
⇒ Done! Kali Linux 'default' metapackage successfully installed in your chroot.\n
⇒ You can start your kali linux cli, using the command >> kali \n
⇒ Enter \"kali -h\" for help.
"