#!/bin/sh -e
# Copyright (c) 2022 iptoux - Maik Roland Damm. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION="Default install that doesn't require GUI."
HOSTBIN='startcli'
CHROOTBIN='croutonpowerd'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

echo "Update the package list..."
apt-get -y -qq update

install dbus openssh-client kbd

install kali-linux-headless -- network-manager

TIPS="$TIPS
Kali Linux 'headless' metapackage successfully installed in your chroot.\n
start a shell in a new VT via the startcli host command: sudo startcli
"